export enum GameHypnoType {
  off = 'off',
  joi = 'joi',
  breeding = 'breeding',
  maledom = 'maledom',
  femdom = 'femdom',
}

export const GameHypnoLabels: Record<GameHypnoType, string> = {
  off: 'Off',
  joi: 'JOI',
  breeding: 'Breeding',
  maledom: 'Maledom Pet',
  femdom: 'Femdom Pet',
};

export const GameHypnoDescriptions: Record<GameHypnoType, string> = {
  off: 'Turn off the hypnosis all-together',
  joi: 'Focus on masturbation encouragement',
  breeding: 'Focus on breeding and primal urge',
  maledom: "Good pets get master's treats",
  femdom: "Good pets get mistress' treats",
};

export const HypnoPhrases: Record<GameHypnoType, string[]> = {
  off: [],
  joi: [
    '$part',
    'stroke',
    'precum',
    'horny',
    'need',
    'instinct',
    "can't stop",
    'ooze',
    'leak',
    '$stroke',
    'hard',
    '$stroke',
    'jack off',
    'give in',
    'obey',
    'pre',
    'must',
    'masturbate',
    'goon',
    '$part',
    'everyday',
  ],
  breeding: [
    'breed',
    'breed',
    'breed her',
    'make her yours',
    'knock her up',
    'reproduce',
    'seed her womb',
    'milk her body',
    'take what\'s yours',
    'mark her',
    'use her',
    'make her submit',
    'make a mess of her',
    'push her limits',
    'break her',
    'harder',
    'deeper',
    'pound her',
    'fuck her senseless',
    'make her scream',
    'ruin her',
    'make her ache for it',
    'leave her dripping',
    'breed her full',
    'let it drip out of her',
    'she needs to be bred',
    'turn her into breeding stock',
    'make her a mother',
    'she\'s made for this',
    'she\'s your toy',
    'hold her down',
    'destroy her',
    'she\'s your cum dumpster',
    'impregnate her',
    'make her beg',
    'she\'s made to take it',
    'she\'s your fucktoy',
    'flood her womb',
    'push it deep',
    'impregnate her',
    'she\'s your breeding slut',
    'fill her up',
    'impregnate her',
    'breed',
    'fill',
    'impregnate',
    'deep',
    'raw',
    'instinct',
    'breedable',
    'breedslut',
    'pulsing',
    'deep',
    'throbbing',
    'instinct',
    'pleasure',
    'raw',
    'fertile',
    'firm',
    'deep',
    'tender',
    'deep',
    'warm',
    'deeper',
    'breed',
    'breeding',
    'fuck',
    'fuck her',
    'shoot',
    'seed',
    'give in',
    'fill her',
    'fill her with your seed',
    'fill her womb',
    'breed her like she\'s in heat',
    'breed her until she\'s addicted to it',
    'fuck her brains out',
    'pin her down',
    'missionary',
    'cowgirl',
    'doggy',
    'breed her gently',
    'cum inside tenderly',
    'impregnate her softly',
    'pound her deeply',
    'cum inside raw',
    'breed her slowly',
    'fill her gently',
    'breed her softly',
    'breed her sweetly',
    'fuck her deeply',
    'fuck her gently',
    'fill her tight pussy',
    'pound her firm body',
    'breed her firm body',
    'she\'s your breeding whore',
    'make her moan softly',
    'pound her soft pussy',
    'breed her tight body',
    'pound her tight ass',
    'breed her firm pussy',
    'impregnate her wet pussy',
    'breed her fertile womb',
    'stuff her womb raw',
    'breed her',
    'breed',
  ],
  maledom: [
    'good $player',
    'hump',
    'listen',
    'stare',
    'obey',
    '$stroke for master',
    '$stroke for master',
    'obey',
    'master',
    'owner',
    'obey',
    'give in',
    'obey master',
    'good $player',
    'good $player',
    'good $player',
    'animal',
    'only',
    'master',
    'give master',
    'not your $part',
    'not your $part',
    'not your $part',
    'not your cum',
    "master's $part",
    "master's $part",
    "master's $part",
    "master's cum",
  ],
  femdom: [
    'good $player',
    'hump',
    'obey',
    'listen',
    'stare',
    'obey',
    '$stroke for mistress',
    '$stroke for mistress',
    'mistress',
    'owner',
    'obey',
    'give in',
    'obey mistress',
    'good $player',
    'good $player',
    'good $player',
    'animal',
    'only',
    'mistress',
    'give mistress',
    'not your $part',
    'not your $part',
    'not your $part',
    'not your cum',
    "mistress' $part",
    "mistress' $part",
    "mistress' $part",
    "mistress' cum",
  ],
};
