export enum GameHypnoType {
  off = 'off',
  joi = 'joi',
  breeding = 'breeding',
  maledom = 'maledom',
  femdom = 'femdom',
}

export const GameHypnoLabels: Record<GameHypnoType, string> = {
  off: 'Off',
  joi: 'JOI',
  breeding: 'Breeding',
  maledom: 'Maledom Pet',
  femdom: 'Femdom Pet',
};

export const GameHypnoDescriptions: Record<GameHypnoType, string> = {
  off: 'Turn off the hypnosis all-together',
  joi: 'Focus on masturbation encouragement',
  breeding: 'Focus on breeding and primal urge',
  maledom: "Good pets get master's treats",
  femdom: "Good pets get mistress' treats",
};

export const HypnoPhrases: Record<GameHypnoType, string[]> = {
  off: [],
  joi: [
    '$part',
    'stroke',
    'precum',
    'horny',
    'need',
    'instinct',
    "can't stop",
    'ooze',
    'leak',
    '$stroke',
    'hard',
    '$stroke',
    'jack off',
    'give in',
    'obey',
    'pre',
    'must',
    'masturbate',
    'goon',
    '$part',
    'everyday',
  ],
  breeding: [
    'breed',
    'breed',
    'breed her',
    'knock her up',
    'reproduce',
    'seed her womb',
    'use her',
    'make her submit',
    'make a mess of her',
    'push her limits',
    'break her',
    'deeper',
    'pound her',
    'ruin her',
    'leave her dripping',
    'breed her full',
    'let it drip out of her',
    'she needs to be bred',
    'make her a mother',
    'she\'s made for this',
    'she\'s your toy',
    'hold her down',
    'destroy her',
    'she\'s your cum dumpster',
    'impregnate her',
    'make her beg',
    'she\'s your fucktoy',
    'flood her womb',
    'make her moan',
    'impregnate her',
    'she\'s your breeding slut',
    'fill her up',
    'impregnate her',
    'breed',
    'fill',
    'impregnate',
    'deep',
    'instinct',
    'breedable',
    'breedslut',
    'pulsing',
    'deep',
    'throbbing',
    'instinct',
    'make her scream',
    'fertile',
    'firm',
    'deep',
    'make her a mother',
    'deep',
    'deeper',
    'breed',
    'breeding',
    'fuck',
    'fuck her',
    'shoot',
    'seed',
    'give in',
    'fill her',
    'make her pregnant',
    'fill her womb',
    'BREED HER',
    'BREED HER',
    'fuck her brains out',
    'pin her down',
    'BREED',
    'breed her gently',
    'dick her down',
    'pound her deeply',
    'cum inside raw',
    'breed her slowly',
    'fill her gently',
    'breed her softly',
    'IMPREGNATE HER',
    'fuck her deeply',
    'fuck her gently',
    'fill her tight pussy',
    'pound her firm body',
    'breed her firm body',
    'she\'s your breeding whore',
    'make her moan softly',
    'pound her soft pussy',
    'breed her tight body',
    'pound her tight ass',
    'breed her firm pussy',
    'impregnate her wet pussy',
    'breed her fertile womb',
    'breed her',
    'breed',
    'breed your older sister',
    'impregnate your older sister',
    'make your big sister pregnant',
    'breed your older sister gently',
    'knock your big sister up',
    'dick down your big sister',
    'make your big sis beg',
    'breed your big sister',
    'impregnate your elder sister',
    'breed your big sister gently',
    'your big sister is your cum dumpster',
    'knock your older sister up',
    'dick down your big sister',
    'make your older sister moan',
    'make your big sister scream',
    'rail your big sister',
    'defile your big sister',
    'defile your elder sister',
    'impregnate your big sister',
    'breed your big sister',
    'impregnate big ltitle sister',
    'fuck your big sister',
    'dick down your older sister',
    'defile your older sister',
    'use your big sister',
    'make your older sister a mother',
    'make a mess out of your big sister',
    'breed your big sister',
    'pound your big sister\'s tight body',
    'your big older is your fucktoy',
    'breed your big sister',
    'impregnate your older sister',
    'breed your big sister',
    'breed your older sister',
    'breed your big sister',
    'dick your younger sister down',
    'your big sister is your toy',
    'big sisters are meant to be bred',
  ],
  maledom: [
    'good $player',
    'hump',
    'listen',
    'stare',
    'obey',
    '$stroke for master',
    '$stroke for master',
    'obey',
    'master',
    'owner',
    'obey',
    'give in',
    'obey master',
    'good $player',
    'good $player',
    'good $player',
    'animal',
    'only',
    'master',
    'give master',
    'not your $part',
    'not your $part',
    'not your $part',
    'not your cum',
    "master's $part",
    "master's $part",
    "master's $part",
    "master's cum",
  ],
  femdom: [
    'good $player',
    'hump',
    'obey',
    'listen',
    'stare',
    'obey',
    '$stroke for mistress',
    '$stroke for mistress',
    'mistress',
    'owner',
    'obey',
    'give in',
    'obey mistress',
    'good $player',
    'good $player',
    'good $player',
    'animal',
    'only',
    'mistress',
    'give mistress',
    'not your $part',
    'not your $part',
    'not your $part',
    'not your cum',
    "mistress' $part",
    "mistress' $part",
    "mistress' $part",
    "mistress' cum",
  ],
};
